name: flutter_city_picker
description: Flutter plugin for city picker, Address picker, Popups widgets, call by function.
version: 2.1.1
homepage: https://github.com/wenchaosong/FlutterCityPicker

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
